// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Polyclinic.Infrastructure.EfCore;

#nullable disable

namespace Polyclinic.Infrastructure.EfCore.Migrations;

[DbContext(typeof(PolyclinicDbContext))]
[Migration("20251210192253_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("Polyclinic.Domain.Models.Appointment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("AppointmentDateTime")
                    .HasColumnType("datetime(6)");

                b.Property<int>("DoctorId")
                    .HasColumnType("int");

                b.Property<bool>("IsFollowUp")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(false);

                b.Property<int>("PatientId")
                    .HasColumnType("int");

                b.Property<int>("RoomNumber")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("AppointmentDateTime");

                b.HasIndex("DoctorId");

                b.HasIndex("PatientId");

                b.HasIndex("Id", "AppointmentDateTime");

                b.ToTable("Appointments");

                b.HasData(
                    new
                    {
                        Id = 1,
                        AppointmentDateTime = new DateTime(2025, 6, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                        DoctorId = 1,
                        IsFollowUp = true,
                        PatientId = 1,
                        RoomNumber = 254
                    },
                    new
                    {
                        Id = 2,
                        AppointmentDateTime = new DateTime(2025, 10, 24, 11, 45, 0, 0, DateTimeKind.Unspecified),
                        DoctorId = 2,
                        IsFollowUp = true,
                        PatientId = 2,
                        RoomNumber = 101
                    },
                    new
                    {
                        Id = 3,
                        AppointmentDateTime = new DateTime(2025, 9, 6, 10, 15, 0, 0, DateTimeKind.Unspecified),
                        DoctorId = 3,
                        IsFollowUp = false,
                        PatientId = 3,
                        RoomNumber = 112
                    },
                    new
                    {
                        Id = 4,
                        AppointmentDateTime = new DateTime(2025, 2, 26, 15, 20, 0, 0, DateTimeKind.Unspecified),
                        DoctorId = 4,
                        IsFollowUp = true,
                        PatientId = 3,
                        RoomNumber = 352
                    },
                    new
                    {
                        Id = 5,
                        AppointmentDateTime = new DateTime(2025, 2, 9, 13, 30, 0, 0, DateTimeKind.Unspecified),
                        DoctorId = 5,
                        IsFollowUp = false,
                        PatientId = 5,
                        RoomNumber = 201
                    },
                    new
                    {
                        Id = 6,
                        AppointmentDateTime = new DateTime(2025, 11, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                        DoctorId = 6,
                        IsFollowUp = false,
                        PatientId = 2,
                        RoomNumber = 405
                    },
                    new
                    {
                        Id = 7,
                        AppointmentDateTime = new DateTime(2025, 2, 27, 10, 0, 0, 0, DateTimeKind.Unspecified),
                        DoctorId = 7,
                        IsFollowUp = true,
                        PatientId = 7,
                        RoomNumber = 201
                    },
                    new
                    {
                        Id = 8,
                        AppointmentDateTime = new DateTime(2025, 5, 27, 16, 15, 0, 0, DateTimeKind.Unspecified),
                        DoctorId = 7,
                        IsFollowUp = false,
                        PatientId = 8,
                        RoomNumber = 123
                    },
                    new
                    {
                        Id = 9,
                        AppointmentDateTime = new DateTime(2025, 6, 30, 12, 30, 0, 0, DateTimeKind.Unspecified),
                        DoctorId = 7,
                        IsFollowUp = false,
                        PatientId = 9,
                        RoomNumber = 241
                    },
                    new
                    {
                        Id = 10,
                        AppointmentDateTime = new DateTime(2025, 8, 15, 14, 50, 0, 0, DateTimeKind.Unspecified),
                        DoctorId = 7,
                        IsFollowUp = true,
                        PatientId = 10,
                        RoomNumber = 118
                    });
            });

        modelBuilder.Entity("Polyclinic.Domain.Models.Doctor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("BirthYear")
                    .HasColumnType("int");

                b.Property<int>("ExperienceYears")
                    .HasColumnType("int");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<string>("PassportNumber")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("varchar(20)");

                b.Property<int>("SpecializationId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("PassportNumber")
                    .IsUnique();

                b.HasIndex("SpecializationId");

                b.ToTable("Doctors");

                b.HasData(
                    new
                    {
                        Id = 1,
                        BirthYear = 1984,
                        ExperienceYears = 10,
                        FullName = "Воробьев Григорий Павлович",
                        PassportNumber = "1854 654123",
                        SpecializationId = 1
                    },
                    new
                    {
                        Id = 2,
                        BirthYear = 1967,
                        ExperienceYears = 26,
                        FullName = "Соколова Галина Михайлова",
                        PassportNumber = "5489 658745",
                        SpecializationId = 2
                    },
                    new
                    {
                        Id = 3,
                        BirthYear = 1977,
                        ExperienceYears = 18,
                        FullName = "Попов Николай Игоревич",
                        PassportNumber = "7598 658234",
                        SpecializationId = 4
                    },
                    new
                    {
                        Id = 4,
                        BirthYear = 1989,
                        ExperienceYears = 8,
                        FullName = "Новиков Анатолий Юрьевич",
                        PassportNumber = "7539 951357",
                        SpecializationId = 5
                    },
                    new
                    {
                        Id = 5,
                        BirthYear = 1980,
                        ExperienceYears = 16,
                        FullName = "Крылова Инна Александровна",
                        PassportNumber = "3984 109283",
                        SpecializationId = 7
                    },
                    new
                    {
                        Id = 6,
                        BirthYear = 1969,
                        ExperienceYears = 31,
                        FullName = "Григорьева Анна Михайловна",
                        PassportNumber = "5984 398623",
                        SpecializationId = 7
                    },
                    new
                    {
                        Id = 7,
                        BirthYear = 1985,
                        ExperienceYears = 11,
                        FullName = "Васнецов Сергей Андреевич",
                        PassportNumber = "5752 757855",
                        SpecializationId = 7
                    },
                    new
                    {
                        Id = 8,
                        BirthYear = 1987,
                        ExperienceYears = 8,
                        FullName = "Орехова Антонина Григорьева",
                        PassportNumber = "7777 777777",
                        SpecializationId = 10
                    },
                    new
                    {
                        Id = 9,
                        BirthYear = 1969,
                        ExperienceYears = 18,
                        FullName = "Малинин Роберт Иванович",
                        PassportNumber = "9999 999999",
                        SpecializationId = 5
                    },
                    new
                    {
                        Id = 10,
                        BirthYear = 1980,
                        ExperienceYears = 15,
                        FullName = "Пашкова Мария Романовна",
                        PassportNumber = "1010 101010",
                        SpecializationId = 4
                    });
            });

        modelBuilder.Entity("Polyclinic.Domain.Models.Patient", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Address")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)");

                b.Property<DateTime>("Birthday")
                    .HasColumnType("datetime(6)");

                b.Property<string>("BloodType")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<string>("Gender")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("PassportNumber")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("varchar(20)");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasMaxLength(15)
                    .HasColumnType("varchar(15)");

                b.Property<string>("RhFactor")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.HasIndex("PassportNumber")
                    .IsUnique();

                b.ToTable("Patients");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Address = "ул. Московская, д.5",
                        Birthday = new DateTime(2003, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        BloodType = "A",
                        FullName = "Петров Петр Петрович",
                        Gender = "Male",
                        PassportNumber = "1234 123456",
                        PhoneNumber = "89271234567",
                        RhFactor = "Positive"
                    },
                    new
                    {
                        Id = 2,
                        Address = "ул. Ленина, д.147, кв 15",
                        Birthday = new DateTime(1980, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        BloodType = "Ab",
                        FullName = "Иванова Мария Романовна",
                        Gender = "Female",
                        PassportNumber = "4321 654321",
                        PhoneNumber = "89945382732",
                        RhFactor = "Positive"
                    },
                    new
                    {
                        Id = 3,
                        Address = "пр. Мира, д. 52, кв 247",
                        Birthday = new DateTime(1978, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        BloodType = "O",
                        FullName = "Сидорова Валентина Ивановна",
                        Gender = "Female",
                        PassportNumber = "1234 582736",
                        PhoneNumber = "89275789245",
                        RhFactor = "Negative"
                    },
                    new
                    {
                        Id = 4,
                        Address = "ул. Победы, д. 23",
                        Birthday = new DateTime(1999, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        BloodType = "B",
                        FullName = "Васильев Василий Васильевич",
                        Gender = "Male",
                        PassportNumber = "1324 459985",
                        PhoneNumber = "89278345655",
                        RhFactor = "Positive"
                    },
                    new
                    {
                        Id = 5,
                        Address = "ул. Таежная, д. 12, кв. 526",
                        Birthday = new DateTime(2004, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        BloodType = "A",
                        FullName = "Смирнова Ольга Олеговна",
                        Gender = "Female",
                        PassportNumber = "1747 452796",
                        PhoneNumber = "89271212121",
                        RhFactor = "Negative"
                    },
                    new
                    {
                        Id = 6,
                        Address = "ул. Московская, д.58, кв. 1",
                        Birthday = new DateTime(2000, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        BloodType = "B",
                        FullName = "Романов Антон Александрович",
                        Gender = "Male",
                        PassportNumber = "6487 123456",
                        PhoneNumber = "89228195847",
                        RhFactor = "Negative"
                    },
                    new
                    {
                        Id = 7,
                        Address = "пр. Гагарина, д.45, кв.3",
                        Birthday = new DateTime(1998, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        BloodType = "A",
                        FullName = "Романова Виктория Сергеевна",
                        Gender = "Female",
                        PassportNumber = "5873 561728",
                        PhoneNumber = "89279414522",
                        RhFactor = "Positive"
                    },
                    new
                    {
                        Id = 8,
                        Address = "ул. Студенческая, д. 18, кв. 76",
                        Birthday = new DateTime(2002, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        BloodType = "Ab",
                        FullName = "Чехов Александр Александрович",
                        Gender = "Male",
                        PassportNumber = "4562 753698",
                        PhoneNumber = "89274924685",
                        RhFactor = "Negative"
                    },
                    new
                    {
                        Id = 9,
                        Address = "ул. Толстова, д.55, кв. 55",
                        Birthday = new DateTime(1985, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        BloodType = "A",
                        FullName = "Иванов Иван Иванович",
                        Gender = "Male",
                        PassportNumber = "5555 555555",
                        PhoneNumber = "89275555555",
                        RhFactor = "Positive"
                    },
                    new
                    {
                        Id = 10,
                        Address = "ул. Авроры, д.372, кв. 185",
                        Birthday = new DateTime(2006, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        BloodType = "B",
                        FullName = "Петрова Оксана Владимировна",
                        Gender = "Female",
                        PassportNumber = "4275 724586",
                        PhoneNumber = "89274523776",
                        RhFactor = "Negative"
                    });
            });

        modelBuilder.Entity("Polyclinic.Domain.Models.Specialization", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.HasKey("Id");

                b.ToTable("Specializations");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Name = "Хирург"
                    },
                    new
                    {
                        Id = 2,
                        Name = "Невролог"
                    },
                    new
                    {
                        Id = 3,
                        Name = "Дерматолог"
                    },
                    new
                    {
                        Id = 4,
                        Name = "Офтальмолог"
                    },
                    new
                    {
                        Id = 5,
                        Name = "Терапевт"
                    },
                    new
                    {
                        Id = 6,
                        Name = "Педиатр"
                    },
                    new
                    {
                        Id = 7,
                        Name = "Стоматолог"
                    },
                    new
                    {
                        Id = 8,
                        Name = "Ортопед"
                    },
                    new
                    {
                        Id = 9,
                        Name = "Кардиолог"
                    },
                    new
                    {
                        Id = 10,
                        Name = "Эндокринолог"
                    });
            });

        modelBuilder.Entity("Polyclinic.Domain.Models.Appointment", b =>
            {
                b.HasOne("Polyclinic.Domain.Models.Doctor", "Doctor")
                    .WithMany()
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Polyclinic.Domain.Models.Patient", "Patient")
                    .WithMany()
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Doctor");

                b.Navigation("Patient");
            });

        modelBuilder.Entity("Polyclinic.Domain.Models.Doctor", b =>
            {
                b.HasOne("Polyclinic.Domain.Models.Specialization", "Specialization")
                    .WithMany()
                    .HasForeignKey("SpecializationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Specialization");
            });
#pragma warning restore 612, 618
    }
}
