<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="AutoMapper" Version="15.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Polyclinic.Contracts\Polyclinic.Contracts.csproj" />
		<ProjectReference Include="..\Polyclinic.Domain\Polyclinic.Domain.csproj" />
		<ProjectReference Include="..\Polyclinic.Application\Polyclinic.Application.csproj" />
		<ProjectReference Include="..\Polyclinic.Infrastructure.EfCore\Polyclinic.Infrastructure.EfCore.csproj" />
		<ProjectReference Include="..\Polyclinic.ServiceDefaults\Polyclinic.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>
